name: actions workflow
on: [push, pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: simple js action
        id: greet
        uses: actions/checkout@v1
      - name: time
        run: echo "${{steps.greet.outputs.time}}" 
