name: demo
on: push
jobs:
  exp-1:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "hello world"
      - uses: actions/checkout@v2
  multi-line:
    runs-on: self-hosted
    steps:
      - name: good-bye
        run: echo "good-bye!!"
      - name: multi-line 
        run: |
          node -v
          npm -v
  windows-commands:
    runs-on: self-hosted
    steps:
      - name: directory bash
        run: pwd
        shell: bash
   
